import re

def extract_emojis(text):
  """Извлекает эмодзи из текста в список."""
  emoji_pattern = re.compile("["
                             u"\U0001F600-\U0001F64F" # эмодзи лиц
                             u"\U0001F300-\U0001F5FF" # символы
                             u"\U0001F680-\U0001F6FF" # транспорт и символы
                             u"\U0001F1E0-\U0001F1FF" # флаги
                             u"\U00002500-\U00002BEF" # различные символы
                             u"\U00002702-\U000027B0"
                             u"\U000024C2-\U0001F251"
                             u"\U0001f926-\U0001f937"
                             u"\U00010000-\U0010ffff"
                             u"\u2600-\u2B55"
                             u"\u200d"
                             u"\u23cf"
                             u"\u23e9"
                             u"\u23ea"
                             u"\u23eb"
                             u"\u23ec"
                             u"\u23ed"
                             u"\u23ee"
                             u"\u23ef"
                             u"\u23f0"
                             u"\u23f1"
                             u"\u23f2"
                             u"\u23f3"
                             u"\u23f8"
                             u"\u23fa"
                             u"\u261d"
                             u"\u2640"
                             u"\u2642"
                             u"\u26a0"
                             u"\u26b0"
                             u"\u26aa"
                             u"\u26ab"
                             u"\u26bd"
                             u"\u26be"
                             u"\u26c4"
                             u"\u26c5"
                             u"\u270c"
                             u"\u270d"
                             u"\u270e"
                             u"\u270f"
                             u"\u2712"
                             u"\u2714"
                             u"\u2716"
                             u"\u271d"
                             u"\u2721"
                             u"\u2728"
                             u"\u2733"
                             u"\u2734"
                             u"\u2744"
                             u"\u2747"
                             u"\u274c"
                             u"\u274e"
                             u"\u2753"
                             u"\u2757"
                             u"\u2763"
                             u"\u2764"
                             u"\u2795"
                             u"\u2796"
                             u"\u2797"
                             u"\u27a1"
                             u"\u27b0"
                             u"\u2934"
                             u"\u2935"
                             u"\u2b05"
                             u"\u2b06"
                             u"\u2b07"
                             u"\u2b1b"
                             u"\u2b1c"
                             u"\u2b50"
                             u"\u2b55"
                             u"\u3030"
                             u"\u303d"
                             u"\u3297"
                             u"\u3299"
                             "]+", flags=re.UNICODE)
  return emoji_pattern.findall(text)