cancel = {"ru": "Отменить", "en": "Cancel"}
welcome = {"ru": "<b>Ты запустил бота впервые!</b>\n\nМы сгенерировали для тебя суперсекретный никнейм (<code>%s</code>), благодаря которому получатели смогут отвечать на твои сообщения\nТы можешь в любое время пересоздать свой суперсекретный ник командой /regen\n\nЧтобы начать получать сообщения, создай себе ссылку командой /link",
           "en": "<b>You've started the bot for the first time!</b>\n\nWe've generated a super secret nickname for you (<code>%s</code>) so that anyone can reply to your messages.\nYou can /regen your super secret nick at any time.\n\nTo start receiving messages, create your own /link"}
edit_link = {"ru": "Изменить ссылку", "en": "Edit link"}
link = {"ru": ["<b>Ссылка на анонимные сообщения 🔗</b>", "<b>Твоя ссылка: </b>", "<i>Ты не можешь принимать анонимные сообщения пока у тебя нет ссылки</i>", 
               "Изменить ссылку", "Поделиться в Telegram", "Отправь мне анонимное сообщение", "📌 Поделись этой ссылкой в соцсетях чтобы начать получать анонимные сообщения"],
        "en": ["<b>Anonymous messages link 🔗</b>", "<b>Your link: </b>", "<i>You can't accept anonymous messages unless you have a link</i>",
               "Edit link", "Share in Telegram", "Send me an anon message", "📌 Share this link on your socials to start receiving anonymous messages"]}
edit_link = {"ru": ["Придумай никнейм, который мы сможем добавить в конец твоей ссылки, чтобы люди смогли начать отправлять тебе анонимные сообщения.", "Бог мёртв.", "Ангел плачет.", "Просто придумай что-то другое...", "В никнейме могут содержаться только буквы английского алфавита, подчёркивания и цифры", "<b>Этот никнейм занят,</b> так что придумай другой."],
             "en": ["Please come up with a new nickname that we can add to the end of your link for users to send you anon messages.", "God is dead.", "Angel is crying.", "Just come up with something else...", "Only English alphabet letters, underscores, numbers can be contained in the nickname", "<b>This nickname is taken,</b> so come up with another one."]}
message_gui = {"ru": ["<b>Новое сообщение</b> от {0}#{1} 📬", "<b>Ответ</b> от {0}#{1} 📬", "↩ <b>Свайпни чтобы ответить</b>"],
               "en": ["<b>New message</b> from {0}#{1} 📬", "<b>Reply</b> from {0}#{1} 📬", "↩ <b>Swipe to reply</b>"]}
special_message_gui = {"ru": "<b>{0}</b> от {1}#{2} 📬", "en": "<b>{0}</b> from {1}#{2} 📬"}
send_message = {"en": ["User #%s was not found, unfortunately.", "Do you want to write a message to yourself? <b>No, you don't.</b",
                       "Write an anon message to {0}#{1}:", "Your message should be text, photo, video, GIF, sticker, document or audio file."],
                "ru": ["Пользователь #%s не был найден, к сожалению.", "Ты хочешь написать самому себе? <b>Нет, не хочешь.</b",
                       "Напиши анонимное сообщение {0}#{1}:", "Твоё сообщение должно быть текстом, фото, видео, GIF, стикером, документом или аудиофайлом."]}
settings = {"en": ["<b>Settings ⚙️</b>\nHere you can customize the bot's work for you", "Language: ", "Emoji: ", "Send me the emoji that users will see when they send you messages before your nickname"],
            "ru": ["<b>Настройки ⚙️</b>\nЗдесь ты можешь настроить работу бота под себя", "Язык: ", "Эмодзи: ", "Отправь эмодзи, которое будут видеть пользователи перед твоим ником при отправке тебе сообщений"]}
secret_id = {"en": "<b>You're a totally different person now! 🪄</b>",
             "ru": "<b>Ну теперь ты совсем другой человек! 🪄</b>"}
languages = {"ru": "🇷🇺", "en": "🇺🇸"}
support = {"en": ["<b>Hello!</b>\n\nThis bot operates solely thanks to the financial and moral support of its users.\nThe donations you contribute will be directed towards maintaining the bot's functionality, developing new projects, and supporting the personal needs of the creator. <b>Your generosity makes a difference!</b>\n\n<b>Thank you for your support! ❤️</b>\n\n<i>With love,\nKeta</i>",
                  "My Telegram", "Donate"],
           "ru": ["<b>Привет!</b>\n\nЭтот бот работает исключительно благодаря вашей финансовой и моральной поддержке.\nПожертвования, которые вы делаете, пойдут на поддержание работоспособности бота, разработку новых проектов и поддержку личных нужд автора. <b>Ваша щедрость имеет значение!</b>\n\n<b>Спасибо за вашу поддержку! ❤️</b>\n\n<i>С любовью,\nКета</i>",
                  "Мой Telegram", "Задонатить"]}
about_you = {"en": "<b>About you 🐱</b>\n\n<b>- You</b>\n<b>Your nickname: </b>{0}\n<i>/regen your nickname if you want</i>\n\n<b>- Link</b>\n<b>Your link: </b><code>{1}</code>\n<i>Change your /link if you want</i>",
             "ru": "<b>О тебе 🐱</b>\n\n<b>- Ты</b>\n<b>Твой никнейм: </b>{0}\n<i>Пересоздай никнейм командой /regen</i>\n\n<b>- Ссылка</b>\n<b>Твоя ссылка: </b><code>{1}</code>\n<i>Ты можешь изменить ссылку командой /link</i>"}
reply = {"en": ["You can't reply to this message because you changed your secret nickname", "This user no longer receives anonymous messages"],
         "ru": ["Ты не можешь ответить на это сообщение так как сменил свой секретный никнейм", "Этот пользователь больше не принимает анонимные сообщения"]}
translate_to = {"en": "Translate", "ru": "Перевести"}
translator = {"en": ["<b>Translation: </b>", "<b>Subscribe for a PREMIUM</b> to translate messages (This will help the project grow)"], "ru": ["<b>Перевод: </b>", "<b>Оформите PREMIUM подписку</b> чтобы переводить сообщения (это поможет проекту развиваться)"]}